### PR TITLE
Degree Pathway Component v2

### PR DESCRIPTION
**Pull request by nbottari9**
Redesigned degree pathway component and added new fields to display
Screenshot 2024-02-20 at 11 06 19 PM

### CODE REVIEW

**Review by Gurpranked — APPROVED** [review]
Looks good, some minor artifacts on the preview. May be specific to the preview. 

image

image

**Comment by nbottari9** [comment]
yeah, so those are the yog fields, degree type fields, etc. once the pathway dialog is finished those should be properly collected and shown. 
Screenshot 2024-02-21 at 12 13 44 PM
you can manually edit the localstorage object if you want and it will show correctly

**Comment by Gurpranked** [comment]
Sounds good, that seems to work. Those fields don't seem to be naturally visible on the local storage info. Adding in the mappings seems to fix the issue.

**Comment by nbottari9** [comment]
yeah theyre not yet, i was gonna leave that to @ultralapse. He's the one working on the pathway dialog.

**Comment by nbottari9** [comment]
And im still gonna keep working on this, I realized I should probably implement update and delete operations for the pathways

**Comment by rajeshrah22** [comment]
Also, I think originally, the tags were meant as a way to track requirements like Arts and Humanites requirements, science with lab requirements, etc. When you create your courses, you would select the tags that a course would satisfy. Does that make sense?

**Comment by Gurpranked** [comment]
I think we really need to outline the attributes of some of the internal objects. Would really define their behavior and subsequent UI. Backend Team Assemble!

**Comment by nbottari9** [comment]
Yeah we should talk more about the tags Thursday, I was a little confused on how thay was supposed to work

**Review by MartinMarwad — APPROVED** [review]

**Pull request merged**
