### PR TITLE
Add Amplify Preview Workflow

### PR DESCRIPTION
**Pull request by MartinMarwad**
#### Overall Review of Changes:
Added a new workflow for getting public PR previews for AWS Amplify. 

##### Reason for Change
Amplify does not support PR previews for public repositories, so this workflow is a workaround. 

#### Tested:
No

### CODE REVIEW

**Comment by MartinMarwad** [comment]
Going to attempt fix for Amplify PR Preview workflow.

**Comment by MartinMarwad** [comment]
Ready to be reviewed and merged 👍 

We'll need to test this for backend environments after that is setup.

**Review by Gurpranked — APPROVED** [review]
Seems good to me!
Nice and clean yaml file to CI/CD with Amplify!

**Review by DaintyJet — APPROVED** [review]
Looks interesting; I think I need to learn more about GitHub Actions.

Approved!

**Pull request merged**
